/**
 */
package com.pnf;

/**
 * PatternType binding type.
 */
public enum PatternType {
    NONE,
    DOUBLE_TOP_BREAKOUT,
    DOUBLE_BOTTOM_BREAKDOWN,
    TRIPLE_TOP_BREAKOUT,
    TRIPLE_BOTTOM_BREAKDOWN,
    QUADRUPLE_TOP_BREAKOUT,
    QUADRUPLE_BOTTOM_BREAKDOWN,
    ASCENDING_TRIPLE_TOP,
    DESCENDING_TRIPLE_BOTTOM,
    BULLISH_CATAPULT,
    BEARISH_CATAPULT,
    BULLISH_SIGNAL_REVERSED,
    BEARISH_SIGNAL_REVERSED,
    BULLISH_TRIANGLE,
    BEARISH_TRIANGLE,
    LONG_TAIL_DOWN,
    HIGH_POLE,
    LOW_POLE,
    BULL_TRAP,
    BEAR_TRAP,
    SPREAD_TRIPLE_TOP,
    SPREAD_TRIPLE_BOTTOM
}
